# Use a SQLite-backed catalog
catalog:
  uri: catalog.db
  init_if_not_exists: true
  writable_storage:
    - ./data
    - duckdb://./data.db
allow_origins:
  - http://localhost:5173
  - http://localhost:5174
